TemporaryPath = "/tmp"

[[Remote]]
Source = "Hello::11"
Target = "Hello::12"
Branches = ["master", "feature", "dev"]

[[Remote]]
Source = "Hello::21"
Target = "Hello::22"

[[Remote]]
Source = "Hello::31"
Target = "Hello::32"
