# fill me with values and put me into ~/.config/gogitmirror.toml

TemporaryPath = "/tmp"
AutoForceFallback = true
#AutoCleanTempFolder = false


[[Credentials]]
Host="github.com"
Username="root"
Password="hunter12"

[[Credentials]]
Host="gitlab.com"
Username="test"
Password="password123"

[[Credentials]]
Host="gitlab.mikescher.com"
Username="NORAD"
Password="joshua"


[[AutoMirror]]
  [AutoMirror.Source]
    Type      = "github"
    RootURL   = "https://github.com"
    Username  = "Mikescher"
  [AutoMirror.Target]
    Type      = "gitlab"
    RootURL   = "https://gitlab.mikescher.com"
    Username  = "Mikescher_mirror"
    OnlyMasterBranch = false


[[Remote]]
Force=true
Source = "https://github.com/Mikescher/BefunUtils.git"
Target = "https://gitlab.mikescher.com/Mikescher/Gitlabtest1.git"
Branches = ["master", "feature", "dev"]
#Force=true

[[Remote]]
Source = "https://github.com/Mikescher/jClipCorn.git"
Target = "https://gitlab.mikescher.com/Mikescher/Gitlabtest2.git"